name: Build and Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build and Release Go Project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
        include:
          - goos: windows
            goarch: amd64
            ext: .exe
          - goos: linux
            goarch: amd64
            ext: ''
          - goos: linux
            goarch: arm64
            ext: ''
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'  # Specify Go version
      - name: Build binary
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o fping-exporter-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}
        env:
          GO111MODULE: on
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fping-exporter-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}
          path: fping-exporter-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Test2
        run: ls -la
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            fping-exporter-linux-amd64
            fping-exporter-linux-arm64
            fping-exporter-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
